<?php

use LojaVirtual\Products\Game;

class GameTest extends PHPUnit\Framework\TestCase
{
    /**
     * @var Game
     */
    protected $game;

    public function testSetGetName()
    {
        $this->game->setName('Fallout 4');

        $this->assertEquals('Fallout 4', $this->game->getName());
    }

    public function testSetGetDescription()
    {
        $this->game->setDescription('Mais um jogo');

        $this->assertEquals('Mais um jogo', $this->game->getDescription());
    }

    public function testSetGetPrice()
    {
        $this->game->setPrice(59.90);

        $this->assertAttributeEquals(59.90, 'price', $this->game);
    }

    public function testSetGetPlatform()
    {
        $this->game->setPlatform('PS4');

        $this->assertInstanceOf(Game::class, $this->game);

        $this->assertEquals('PS4', $this->game->getPlatform());
    }

    protected function setUp()
    {
        $this->game = new Game();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}

